# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  searchservice:
    image: searchservice
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5246:5246
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
