# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  identityserver:
    image: identityserver
    build:
      context: .
      dockerfile: src/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres; User Id =postgres;Password=postgrespw; Database=identity
    ports:
      - 5001:80
 

