# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # auctionservice:
  #   image: auctionservice
  #   build:
  #     context: .
  #     dockerfile: src/AuctionService/Dockerfile
  #   ports:
  #     - 5151:5151

volumes:
  pgdata: